-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cards
(
    card_id uuid NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    damage integer NOT NULL,
    element character varying(20) COLLATE pg_catalog."default",
    type character varying(20) COLLATE pg_catalog."default",
    player_id uuid,
    locked boolean DEFAULT false,
    CONSTRAINT cards_pkey PRIMARY KEY (card_id)
);

CREATE TABLE IF NOT EXISTS public.decks
(
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    card_id uuid NOT NULL,
    CONSTRAINT decks_pkey PRIMARY KEY (username, card_id)
);

CREATE TABLE IF NOT EXISTS public.player_cards
(
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    card_id uuid NOT NULL,
    CONSTRAINT player_cards_pkey PRIMARY KEY (username, card_id)
);

CREATE TABLE IF NOT EXISTS public.players
(
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(256) COLLATE pg_catalog."default" NOT NULL,
    elo integer DEFAULT 100,
    coins integer DEFAULT 20,
    games_played integer DEFAULT 0,
    failed_attempts integer DEFAULT 0,
    lockout_until timestamp without time zone,
    token character varying(255) COLLATE pg_catalog."default",
    token_expiry timestamp without time zone,
    player_id uuid DEFAULT gen_random_uuid(),
    CONSTRAINT players_pkey PRIMARY KEY (username),
    CONSTRAINT unique_player_id UNIQUE (player_id)
);

CREATE TABLE IF NOT EXISTS public.trades
(
    trade_id uuid NOT NULL,
    requester_username character varying(50) COLLATE pg_catalog."default",
    card_id uuid,
    required_type character varying(20) COLLATE pg_catalog."default",
    required_element character varying(20) COLLATE pg_catalog."default",
    min_damage integer,
    is_completed boolean DEFAULT false,
    CONSTRAINT trades_pkey PRIMARY KEY (trade_id)
);

ALTER TABLE IF EXISTS public.cards
    ADD CONSTRAINT fk_player FOREIGN KEY (player_id)
    REFERENCES public.players (player_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.decks
    ADD CONSTRAINT decks_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES public.cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.decks
    ADD CONSTRAINT decks_username_fkey FOREIGN KEY (username)
    REFERENCES public.players (username) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.player_cards
    ADD CONSTRAINT player_cards_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES public.cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.player_cards
    ADD CONSTRAINT player_cards_username_fkey FOREIGN KEY (username)
    REFERENCES public.players (username) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.trades
    ADD CONSTRAINT trades_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES public.cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.trades
    ADD CONSTRAINT trades_requester_username_fkey FOREIGN KEY (requester_username)
    REFERENCES public.players (username) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

INSERT INTO cards (card_id, name, damage, element, type, player_id) VALUES
(gen_random_uuid(), 'Fire Dragon', 80, 'FIRE', 'MONSTER', NULL),
(gen_random_uuid(), 'Water Serpent', 75, 'WATER', 'MONSTER', NULL),
(gen_random_uuid(), 'Earth Golem', 90, 'NORMAL', 'MONSTER', NULL),
(gen_random_uuid(), 'Lightning Mage', 65, 'FIRE', 'SPELL', NULL),
(gen_random_uuid(), 'Ice Blast', 70, 'WATER', 'SPELL', NULL),
(gen_random_uuid(), 'Rock Slam', 60, 'NORMAL', 'SPELL', NULL),
(gen_random_uuid(), 'Blazing Inferno', 85, 'FIRE', 'SPELL', NULL),
(gen_random_uuid(), 'Aqua Knight', 77, 'WATER', 'MONSTER', NULL),
(gen_random_uuid(), 'Stone Titan', 88, 'NORMAL', 'MONSTER', NULL),
(gen_random_uuid(), 'Phoenix Rebirth', 95, 'FIRE', 'MONSTER', NULL),
(gen_random_uuid(), 'Tsunami Wave', 82, 'WATER', 'SPELL', NULL),
(gen_random_uuid(), 'Boulder Crash', 74, 'NORMAL', 'SPELL', NULL);

END;